#version: "3.9"

services:
  # FROM "tournament-manager-api/docker-compose.yml"
  mongo:
    image: mongo:6.0 
    container_name: tournament-designer-db
    restart: always
    ports:
      - "27017:27017"
    networks:
      - internal_net
    volumes:
      - mongo_data:/data/db
  
  # FROM "tournament-manager-ui/docker-compose.yml"
  angular-app:
    build:
      context: ./tournament-manager-ui
      dockerfile: Dockerfile
    container_name: angular_app
    ports:
      - "80:80"
    networks:
      - internal_net
    restart: unless-stopped

  # NEW 
  # Kafka configuration docs: https://docs.confluent.io/platform/current/installation/docker/config-reference.html
  # Kafka configuration ref: https://developer.confluent.io/confluent-tutorials/kafka-on-docker/ https://hub.docker.com/r/bitnami/kafka
  kafka:
    image: bitnami/kafka:latest
    networks:
      - internal_net
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0 
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami/kafka
  
  # FROM "tournament-manager-api/docker-compose.yml"
  api:
    build: ./tournament-manager-api #Change Path
    container_name: tournament-designer-api
    ports:
      - "3000:3000"
    networks:
      - internal_net
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/tournament_designer

      #  ===== Added for Kafka ===== 
      - KAFKA_BROKER=kafka:9092         
      - KAFKA_TOPIC=torneos
      #  ===== Added for Kafka ===== 

    volumes:
      - ./tournament-manager-api:/app #Change NEW Path
      - /app/node_modules
    depends_on:
      - mongo
      - kafka
    command: npm run dev

  # NEW
  # Chaty  
  job:
    build: ./job
    networks:
      - internal_net
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=torneos
    depends_on: 
      - kafka

volumes:
  mongo_data:
  kafka_data:

networks:
  internal_net:
    driver: bridge
