#docker volume pruneversion: "3.9"

services:
  api:
    build: .
    container_name: api
    ports:
      - "3000:3000"
    networks:
      - internal_net
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/tournament_designer
      #  ===== Added for Kafka ===== 
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=torneos
      #  ===== Added for Kafka ===== 
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    command: npm run dev
    
  mongo:
    image: mongo:6.0
    container_name: db
    restart: always
    ports:
      - "27017:27017"
    networks:
      - internal_net
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

networks:
  internal_net:
    driver: bridge
